vich_uploader:
    db_driver: orm

    mappings:
         featured_image:
             uri_prefix: '%app.path.featured_image%'
             upload_destination: '%kernel.project_dir%/public/%app.path.featured_image%'
